# Generated by Django 5.0.4 on 2024-05-17 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_note_delete_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='stockName',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='stockSymbol',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to=settings.AUTH_USER_MODEL),
        ),
    ]
