# Generated by Django 5.0.4 on 2024-05-17 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_note_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchList',
            new_name='Note',
        ),
    ]
